import Foundation
import AVFoundation
import UIKit
@MainActor final class ExportStore:ObservableObject{
 @Published private(set)var records:[ExportRecord]=[];@Published var error:String?;private let fm=FileManager.default
 init(){load()}
 func importFiles(_ urls:[URL]){for u in urls{let access=u.startAccessingSecurityScopedResource();defer{if access{u.stopAccessingSecurityScopedResource()}};let d=imports().appendingPathComponent(u.lastPathComponent);try? fm.removeItem(at:d);try? fm.copyItem(at:u,to:d)}}
 func importedURLs()->[URL]{(try? fm.contentsOfDirectory(at:imports(),includingPropertiesForKeys:nil).filter{!$0.lastPathComponent.hasPrefix(".")}) ?? []}
 func export(_ source:URL)async{do{guard let a=try PackageInspector.assets(in:source).first else{throw ExportError.unsupported};let o=exports().appendingPathComponent("\(source.deletingPathExtension().lastPathComponent)-\(UUID().uuidString.prefix(6)).mp4");if ["MP4","MOV","M4V"].contains(a.kind){try await transcode(a.url,to:o)}else{try await still(a.url,to:o)};records.insert(.init(id:UUID(),name:o.deletingPathExtension().lastPathComponent,filename:o.lastPathComponent,createdAt:Date()),at:0);save()}catch{error=error.localizedDescription}}
 func url(for r:ExportRecord)->URL{exports().appendingPathComponent(r.filename)}
 func delete(_ r:ExportRecord){try?fm.removeItem(at:url(for:r));records.removeAll{$0.id==r.id};save()}
 private func transcode(_ i:URL,to o:URL)async throws{let a=AVAsset(url:i);guard let e=AVAssetExportSession(asset:a,presetName:AVAssetExportPresetHighestQuality)else{throw ExportError.failed};e.outputURL=o;e.outputFileType=.mp4;try await withCheckedThrowingContinuation{(c:CheckedContinuation<Void,Error>)in e.exportAsynchronously{e.status == .completed ? c.resume():c.resume(throwing:e.error ?? ExportError.failed)}}}
 private func still(_ i:URL,to o:URL)async throws{guard let image=UIImage(contentsOfFile:i.path),let cg=image.cgImage else{throw ExportError.failed};let w=min(max(cg.width,2),4096),h=min(max(cg.height,2),4096);let writer=try AVAssetWriter(outputURL:o,fileType:.mp4);let input=AVAssetWriterInput(mediaType:.video,outputSettings:[AVVideoCodecKey:AVVideoCodecType.h264,AVVideoWidthKey:w,AVVideoHeightKey:h]);let adaptor=AVAssetWriterInputPixelBufferAdaptor(assetWriterInput:input);writer.add(input);writer.startWriting();writer.startSession(atSourceTime:.zero);var pixel:CVPixelBuffer?;CVPixelBufferCreate(nil,w,h,kCVPixelFormatType_32BGRA,[kCVPixelBufferCGImageCompatibilityKey:true,kCVPixelBufferCGBitmapContextCompatibilityKey:true] as CFDictionary,&pixel);guard let pixel else{throw ExportError.failed};CVPixelBufferLockBaseAddress(pixel,[]);if let base=CVPixelBufferGetBaseAddress(pixel){let ctx=CGContext(data:base,width:w,height:h,bitsPerComponent:8,bytesPerRow:CVPixelBufferGetBytesPerRow(pixel),space:CGColorSpaceCreateDeviceRGB(),bitmapInfo:CGImageAlphaInfo.premultipliedFirst.rawValue|CGBitmapInfo.byteOrder32Little.rawValue);ctx?.draw(cg,in:CGRect(x:0,y:0,width:w,height:h))};CVPixelBufferUnlockBaseAddress(pixel,[]);for n in 0..<90{while !input.isReadyForMoreMediaData{try await Task.sleep(for:.milliseconds(5))};adaptor.append(pixel,withPresentationTime:CMTime(value:CMTimeValue(n),timescale:30))};input.markAsFinished();await writer.finishWriting();guard writer.status==.completed else{throw writer.error ?? ExportError.failed}}
 private func base()->URL{let u=fm.urls(for:.applicationSupportDirectory,in:.userDomainMask)[0].appendingPathComponent("LumaForge",isDirectory:true);try?fm.createDirectory(at:u,withIntermediateDirectories:true);return u}
 private func imports()->URL{let u=base().appendingPathComponent("Imports",isDirectory:true);try?fm.createDirectory(at:u,withIntermediateDirectories:true);return u}
 private func exports()->URL{let u=base().appendingPathComponent("Exports",isDirectory:true);try?fm.createDirectory(at:u,withIntermediateDirectories:true);return u}
 private func manifest()->URL{base().appendingPathComponent("exports.json")}
 private func load(){guard let d=try?Data(contentsOf:manifest()),let r=try?JSONDecoder().decode([ExportRecord].self,from:d)else{return};records=r}
 private func save(){try?JSONEncoder().encode(records).write(to:manifest(),options:.atomic)}
}